import 'package:flutter/material.dart';
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';
import 'home_page.dart';
import 'models/todo_model.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  //get the path to store the database locally
  final dir = await getApplicationDocumentsDirectory();
  //get an instance of the database for use, the list of schemas are the ones generated by isar on classes annotated by @collection. Basically all model classes go here.
  final isar = await Isar.open([TodoSchema], directory: dir.path);
  runApp(MyApp(isar: isar));
}

class MyApp extends StatelessWidget {
  final Isar isar;
  const MyApp({super.key, required this.isar});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: HomePage(isar), debugShowCheckedModeBanner: false);
  }
}
